version: "2"
services:
  #nuxtjs
  nuxtjs:
    image: node:12
    volumes:
      - ./server:/home/node
      - node_modules_nuxtjs:/home/node/node_modules
    working_dir: /home/node
  install-nuxtjs:
    extends:
      service: nuxtjs
    command: yarn install
  build-nuxtjs:
    extends:
      service: nuxtjs
    command: yarn run build

  #db-migrate
  # has different package.json
  db-migrate:
    image: node:12
    volumes:
      - ./db-migrate:/home/node
      - node_modules_db-migrate:/home/node/node_modules
    working_dir: /home/node
  install-db-migrate:
    extends:
      service: db-migrate
    command: yarn install
  build-db-migrate:
    extends:
      service: db-migrate
    command: yarn run build

volumes:
  node_modules_nuxtjs:
  node_modules_db-migrate:
